Reverted changes to batch size
because otherwise the training fails after a while although memory is not fully used. See : 
 File "synthesizer_train.py", line 35, in <module>
    train(**vars(args))
  File "/content/Real-Time-Voice-Cloning/synthesizer/train.py", line 188, in train
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([28, 256, 1, 33], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(256, 256, kernel_size=[1, 2], padding=[0, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x558a0dc2c300
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 28, 256, 1, 33, 
    strideA = 8448, 33, 33, 1, 
output: TensorDescriptor 0x558a0dc2c290
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 28, 256, 1, 34, 
    strideA = 8704, 34, 34, 1, 
weight: FilterDescriptor 0x558a0d941860
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 256, 256, 1, 2, 
Pointer addresses: 
    input: 0x7fccaf6ee000
    output: 0x7fccaf600000
    weight: 0x7fcc9bd25a00
Additional pointer addresses: 
    grad_output: 0x7fccaf600000
    grad_input: 0x7fccaf6ee000
Backward data algorithm: 1