Used binary_cross_entropy_with_logits for stoploss
Did the change in both training and validation steps because otherwise there was a runtime error when using 16 bit precision.
Error and hint were : 
>RuntimeError: torch.nn.functional.binary_cross_entropy and torch.nn.BCELoss are unsafe to autocast.
		Many models use a sigmoid layer right before the binary cross entropy layer.
		In this case, combine the two layers using torch.nn.functional.binary_cross_entropy_with_logits
		or torch.nn.BCEWithLogitsLoss.  binary_cross_entropy_with_logits and BCEWithLogits are
		safe to autocast.